### ISSUE TITLE
dmobs.regulars can never be set to false

### ISSUE THREAD

**Issue by hdak1945git** [D00Med/dmobs#14]
Around [init.lua:11](https://github.com/D00Med/dmobs/blob/master/init.lua#L11) there are several configuration options available however some are unchangeable.

```lua
dmobs.regulars = minetest.setting_getbool("dmobs.regulars") or true
```

`minetest.setting_getbool` returns `nil` when a given variable is undefined, in this case though unfortunately, it is converted to `false` when used with logical `or`. Thus this statement can never be set to `false`.

I've made a patch [here](https://gist.github.com/hdak1945git/578f0e1fc747a1808ae873ad7f00a3ba) that explicitly tests for `nil`, but it also separates baddies from the "regulars" that you may or may not want.

**Comment by taikedz** [comment]
My bad I inserted that bug. I'll patch it in my version an PR

EDIT -- baddies are disabled by the `mobs_redo` setting and removing them via the code was cancelled in https://github.com/D00Med/dmobs/pull/10

D00Med to confirm which version he wants to keep.

**Comment by D00Med** [comment]
Thankyou for pointing this out.

**Comment by hdak1945git** [comment]
So far, setting `only_peaceful_mobs` to true seems to do what I want for the most part.. (thanks @taikedz -- I was unaware of that cross-mod interaction) Now I don't need to apply a good chunk of my patch to boot.

For future reference: [api.txt](https://github.com/tenplus1/mobs_redo/blob/e3515482cc636d4b84b7363b4815bf24ebdfe220/api.txt#L9)

**Comment by D00Med** [comment]
This is all fixed now right?

**Comment by taikedz** [comment]
The pull you accepted fixed the issues so far reported here.
