### ISSUE TITLE
Spawn drake cause Crash Error! 

### ISSUE THREAD

**Issue by antysuckers123** [D00Med/dmobs#16]
I tryed everything but i need help ! 
 ERROR[Main]: ServerError: Lua: Runtime error from mod 'dmobs' in callback luaentity_Step(): ...ktop\minetest-0.4.15-win64\bin\..\mods\mobs_redo/api.lua:1276: attempt to compare nil with number

**Comment by D00Med** [comment]
Is that all of the error?

**Comment by taikedz** [comment]
Looks like it *might* be related to mobs_redo code for dogshoot mode switching.

@antysuckers123 Have you tried with the latest? https://github.com/tenplus1/mobs_redo/archive/master.zip Also, what mob specifically?

**Comment by antysuckers123** [comment]
Ofc i'm not sure if dmobs is the problem or mobs_redo but here i got the full ERROR!  ERROR[Main]: ServerError: Lua: Runtime error from mod 'dmobs' in callback luaentity_Step(): ...r\Desktop\minetest-0.4.15-win64\bin\..\mods\mobs/api.lua:1276: attempt to compare nil with number
2017-03-27 23:14:28: ERROR[Main]: stack traceback:
2017-03-27 23:14:28: ERROR[Main]:       ...r\Desktop\minetest-0.4.15-win64\bin\..\mods\mobs/api.lua:1276: in function 'dogswitch'
2017-03-27 23:14:28: ERROR[Main]:       ...r\Desktop\minetest-0.4.15-win64\bin\..\mods\mobs/api.lua:1578: in function 'do_states'
2017-03-27 23:14:28: ERROR[Main]:       ...r\Desktop\minetest-0.4.15-win64\bin\..\mods\mobs/api.lua:2335: in function <...r\Desktop\minetest-0.4.15-win64\bin\..\mods\mobs/api.lua:2228>     
I make this short i have no problem to spawn any animals or monster but if i spawn a Drake it crashe's and i get that ERROR ye i could play without the drakes but i like them that much! DMOBS works on DuCakesVivarium but if i try to install them not. why???

**Comment by D00Med** [comment]
@taikedz Isn't this that problem I decided not to fix because I was going to remake the mod?

**Comment by antysuckers123** [comment]
It worked with the new mobs_redo! But how i searched for the latest mobs_redo and didn't get it but never mind i thank u guys!

**Comment by D00Med** [comment]
Oh ok, glad you got it sorted out

**Comment by taikedz** [comment]
Can't remember which issue it was that you were going to let slip pending the remake...

But I suspect it was a bug in mobs_redo which was fixed only yesterday https://github.com/tenplus1/mobs_redo/commit/e1f7453ee52c280af7c243cbe6290d14b692a0d4

**Comment by D00Med** [comment]
Oh ok., that looks like it might be it

**Comment by antysuckers123** [comment]
This is probably an issue too.
![drake](https://cloud.githubusercontent.com/assets/26663641/24381489/d619b73e-1350-11e7-8026-7bfaa7c5ca9e.png)
